import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { writeArrayBuffer } from "geotiff";
import { decodeNdviScene, SceneDecodeError, MAX_SCENE_PIXELS } from "@/lib/gis/satellite/decode";

/**
 * The decoder is the one genuinely-unbuilt P2 piece (council-flagged). Validate against the SAME Python
 * `tifffile` output P0 used — element-for-element on the band values AND on the georeferencing — because a
 * silent band-order/FLOAT32/axis mistake would corrupt every NDVI reading and look like real vineyard data.
 *
 * The fixture is a real ~0.6 km CDSE scene (55×66, EPSG 32617), regenerated by scripts/gis-p2-make-fixture.ts.
 * The band oracle is Python tifffile (base64 in the reference JSON → no Python in CI); the georeference oracle
 * is the REQUEST (utmBboxFor), both independent of geotiff.js.
 */
const TIF = readFileSync(fileURLToPath(new URL("./fixtures/gis/ndvi-scene.tif", import.meta.url)));
type Reference = {
  width: number;
  height: number;
  red: string;
  nir: string;
  scl: string;
  georef: { crsEpsg: number; pixelSizeM: number; axisYSign: number; requestUtmBbox: [number, number, number, number] };
};
const REF = JSON.parse(readFileSync(fileURLToPath(new URL("./fixtures/gis/ndvi-scene-reference.json", import.meta.url)), "utf8")) as Reference;
const b64ToF32 = (b64: string): Float32Array => {
  const buf = Buffer.from(b64, "base64");
  return new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
};

describe("decodeNdviScene — the committed real-scene fixture", () => {
  it("decodes the band planes identical to the Python tifffile oracle, element-for-element", async () => {
    const scene = await decodeNdviScene(new Uint8Array(TIF));
    expect(scene.width).toBe(REF.width);
    expect(scene.height).toBe(REF.height);

    // Each band is a Float32Array (memory contract, council C6) — not number[].
    expect(scene.red).toBeInstanceOf(Float32Array);
    expect(scene.nir).toBeInstanceOf(Float32Array);
    expect(scene.scl).toBeInstanceOf(Float32Array);

    const refRed = b64ToF32(REF.red);
    const refNir = b64ToF32(REF.nir);
    const refScl = b64ToF32(REF.scl);
    expect(scene.red.length).toBe(refRed.length);
    // Bit-exact: same FLOAT32 file, two readers. (Iterate rather than toEqual for a clearer failure locus.)
    for (let i = 0; i < refRed.length; i++) {
      expect(scene.red[i]).toBe(refRed[i]);
      expect(scene.nir[i]).toBe(refNir[i]);
      expect(scene.scl[i]).toBe(refScl[i]);
    }
  });

  it("reads the georeferencing back to match the request oracle (origin, pixelSize, axis, EPSG, bbox)", async () => {
    const scene = await decodeNdviScene(new Uint8Array(TIF));
    const g = REF.georef;
    expect(scene.crsEpsg).toBe(g.crsEpsg); // exact — proves the geokey read
    expect(scene.axisYSign).toBe(g.axisYSign); // -1, north-up (origin at the top edge)
    // CDSE fits an integer pixel count across the AOI, so the ACTUAL pixel size drifts sub-metre from the
    // requested 10 m (≈ bboxWidth / width). Assert near-10 (never bilinear-blurred) AND that the geotransform
    // is INTERNALLY CONSISTENT — the property the clipper actually depends on.
    expect(Math.abs(scene.pixelSizeM - g.pixelSizeM)).toBeLessThan(0.5);
    expect(scene.originX + scene.width * scene.pixelSizeM).toBeCloseTo(scene.bbox[2], 3); // right edge = max X
    expect(scene.originY - scene.height * scene.pixelSizeM).toBeCloseTo(scene.bbox[1], 3); // bottom edge = min Y (north-up)

    // Origin/bbox snap to CDSE's grid; assert within one pixel of the requested UTM bbox.
    const tol = g.pixelSizeM;
    expect(Math.abs(scene.originX - g.requestUtmBbox[0])).toBeLessThanOrEqual(tol); // left edge = min X
    expect(Math.abs(scene.originY - g.requestUtmBbox[3])).toBeLessThanOrEqual(tol); // top edge = max Y (north-up)
    expect(Math.abs(scene.bbox[0] - g.requestUtmBbox[0])).toBeLessThanOrEqual(tol);
    expect(Math.abs(scene.bbox[1] - g.requestUtmBbox[1])).toBeLessThanOrEqual(tol);
    expect(Math.abs(scene.bbox[2] - g.requestUtmBbox[2])).toBeLessThanOrEqual(tol);
    expect(Math.abs(scene.bbox[3] - g.requestUtmBbox[3])).toBeLessThanOrEqual(tol);

    // The SCL band carries only integer class codes (DN), never fractional — proves NEAREST, not bilinear.
    for (let i = 0; i < scene.scl.length; i++) expect(Number.isInteger(scene.scl[i])).toBe(true);
  });
});

describe("decodeNdviScene — the council C6 rejection contract", () => {
  it("rejects a non-TIFF buffer", async () => {
    await expect(decodeNdviScene(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]))).rejects.toMatchObject({ name: "SceneDecodeError", fault: "not-tiff" });
  });

  it("rejects an empty/short buffer as truncated", async () => {
    await expect(decodeNdviScene(new Uint8Array([0x49, 0x49]))).rejects.toMatchObject({ fault: "truncated" });
  });

  it("rejects a BigTIFF (version 43) up front with the typed error", async () => {
    // Little-endian "II", version word 43 (BigTIFF), then padding.
    const big = new Uint8Array([0x49, 0x49, 0x2b, 0x00, 0x08, 0x00, 0x00, 0x00, 0, 0, 0, 0]);
    await expect(decodeNdviScene(big)).rejects.toMatchObject({ name: "SceneDecodeError", fault: "bigtiff" });
  });

  it("rejects a valid-header-but-truncated TIFF", async () => {
    // Keep the 8-byte header (valid magic + version), drop the IFD → the parse fails.
    await expect(decodeNdviScene(new Uint8Array(TIF).slice(0, 8))).rejects.toBeInstanceOf(SceneDecodeError);
  });

  it("rejects a real single-band GeoTIFF (samplesPerPixel !== 3)", async () => {
    const w = 4;
    const h = 3;
    const values = new Float32Array(w * h).fill(0.2);
    const oneBand = await writeArrayBuffer(values, {
      width: w,
      height: h,
      ModelPixelScale: [10, 10, 0],
      ModelTiepoint: [0, 0, 0, 700000, 4200000, 0],
      GeographicTypeGeoKey: 32617,
    });
    await expect(decodeNdviScene(new Uint8Array(oneBand as ArrayBuffer))).rejects.toMatchObject({ fault: "band-count" });
  });

  it("exposes a memory ceiling well above estate scale but below OOM", () => {
    expect(MAX_SCENE_PIXELS).toBeGreaterThan(1_000_000); // estate ~0.12 M px fits comfortably
    expect(MAX_SCENE_PIXELS).toBeLessThanOrEqual(4_000_000);
  });
});
