/**
 * FK-1 guard — every foreign key in `schema.prisma` is either a Prisma relation or a declared
 * composite constraint. No FK column may be undeclared in both places.
 *
 * THE PROBLEM IT CLOSES. Composite `(tenantId, refId) → (tenantId, id)` FKs make a cross-tenant
 * reference structurally impossible, which is a property worth keeping — but Prisma cannot express them,
 * so 42% of models carry FK columns with no `@relation`. Before this guard, the ONLY record that such a
 * constraint existed was a line of SQL inside one of 186 migrations. Nothing checked that:
 *   - a new `*Id` column ever got its constraint written, or
 *   - a constraint someone dropped was noticed.
 * A new table could ship with a dangling reference column and every test would pass.
 *
 * HOW IT WORKS. `prisma/fk-registry.json` (generated by `gen:fk-registry`, replayed from the migration
 * history) is the declared graph. This scan reads `schema.prisma` and, for every model, asserts each
 * reference-looking column is covered by EITHER a Prisma `@relation` OR a registry constraint on that
 * model's table. Anything else must be on ALLOWED with a stated reason — those are the columns that only
 * LOOK like foreign keys (external provider ids, opaque handles), and naming them explicitly is the point.
 *
 * Pure static scan. No DB, no typechecker. The companion `verify:fk-registry-db` proves the registry
 * matches `information_schema` on a real database — two independent derivations of the same graph.
 *
 * Known limitations (tripwire, not a proof):
 *   - It proves a constraint is DECLARED, not that the declared target is the semantically right table.
 *   - Column-name heuristic (`…Id`). A reference column named otherwise is invisible to it.
 *
 *   npm run verify:fk-registry   (or: npx tsx scripts/check-fk-registry.ts)
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

type Registry = {
  constraints: { constraint: string; table: string; columns: string[]; refTable: string }[];
};

/**
 * Columns that look like a reference but are NOT a foreign key. Each needs a reason — this list is the
 * audit trail for "we looked at it and it genuinely points nowhere in our database".
 * Key is `Model.column`.
 */
const ALLOWED = new Map<string, string>([
  // Opaque ids issued by US/EU government or satellite providers — no local table to reference.
  ["VineyardWeatherConfig.stationId", "RCC-ACIS station id (external provider handle)"],
  ["VineyardWeatherConfig.stationOverrideId", "RCC-ACIS station id chosen by the grower (external)"],
  ["VineyardWeatherConfig.nwsGridId", "NOAA/NWS forecast-grid id (external)"],
  ["SpatialScene.providerSceneId", "Copernicus/CDSE scene id (external)"],
  // Code-like identifiers that are validated against a code table in app code, not a DB table.
  ["SpatialStyle.paletteId", "palette code validated in app code; no palette table exists"],
  // Audit rows deliberately do NOT constrain their subject: the row must survive the subject's deletion.
  ["AuditLog.entityId", "polymorphic subject; an audit row must outlive the row it describes"],
  ["AuditLog.actorUserId", "actor snapshot; the audit trail must survive user deletion"],
  // Location is a REAL composite FK on other tables (cellar_material, supply_lot); on these four it is
  // deliberately a plain ref, documented in the schema at the column. Listed PER COLUMN and not by name
  // for exactly that reason — a name-based exemption would silently excuse the genuine ones too.
  ["WorkOrder.locationId", "plan 053 B9: plain ref -> location.id, resolved at runtime (schema.prisma:5040)"],
  ["WorkOrderTask.locationId", "plan 053 B9: plain ref -> location.id, resolved at runtime (schema.prisma:5210)"],
  ["EquipmentAsset.locationId", "plain ref -> location.id, K11/K12 (schema.prisma:5098)"],
  ["Commerce7SkuMap.locationId", "our finished-goods Location as a plain ref (schema.prisma:4801)"],
]);

/** Reference-looking column names that are never foreign keys. */
const NEVER_FK = new Set(["id", "externalId", "requestId", "commandId", "idempotencyKey", "correlationId"]);

/**
 * Column NAMES that are deliberately unconstrained wherever they appear, by category. These are not
 * exemptions of convenience — each category has a structural reason a foreign key is impossible or wrong.
 * Keeping them as named categories (rather than 100 individual entries) is what keeps the guard's
 * remaining output small enough to actually read.
 */
const SOFT_REFERENCE: { reason: string; columns: string[] }[] = [
  {
    reason:
      "ACTOR SNAPSHOT → the GLOBAL `user` table. A composite (tenantId, userId) FK is IMPOSSIBLE — `user` " +
      "carries no tenantId (it is on the auth denylist) — and a simple FK would make a user undeletable " +
      "for as long as any history mentions them. Every one of these is paired with an email snapshot " +
      "column so the record stays readable after the account is gone. Same rationale as AuditLog.actorUserId.",
    columns: [
      "createdById", "enteredById", "actorUserId", "userId", "confirmedById", "voidedById", "startedById",
      "resolvedByUserId", "assigneeId", "askedByUserId", "answeredByUserId", "approvedByUserId",
      "linkedByUserId", "reporterUserId", "ratedById", "issuedById", "completedById", "rejectedById",
      "sessionId",
    ],
  },
  {
    reason:
      "EXTERNAL IDENTIFIER issued by a third-party system (QuickBooks, Commerce7, GitHub, Copernicus, " +
      "NOAA, RCC-ACIS, Better Auth's OAuth providers). There is no local row to reference.",
    columns: [
      "externalVendorId", "externalSystemId", "commerce7OrderId", "workflowRunId", "providerSceneId",
      "accountId", "providerId", "stationId", "stationOverrideId", "nwsGridId", "linearIssueId",
    ],
  },
  {
    reason:
      "CORRELATION KEY — groups sibling rows (the two legs of a transfer, one import batch, one sweep run, " +
      "one client submission). It is a shared label, not a pointer at a row, so there is nothing to constrain.",
    columns: ["transferGroupId", "batchId", "runId", "clientRequestId"],
  },
];

const softReason = new Map<string, string>();
for (const g of SOFT_REFERENCE) for (const c of g.columns) softReason.set(c, g.reason);

/**
 * RATCHET. 89 reference columns predate this guard. Triaging each one is a domain decision (is
 * `Lot.originVineyardId` a constraint we forgot, or a deliberate snapshot that must survive the
 * vineyard's deletion?), and blocking the guard on that would mean shipping no protection at all
 * meanwhile. So the pre-existing set is a BASELINE: the guard fails on anything NEW, and the baseline is
 * a visible backlog to shrink. Same pattern as `verify:ai-native`'s ratcheted allow-list.
 *
 * Shrinking it is the work: either write the missing constraint (and re-run `gen:fk-registry`), or move
 * the column into SOFT_REFERENCE / ALLOWED with the reason it can never have one. Never add to it.
 */
const BASELINE_PATH = join(process.cwd(), "prisma", "fk-baseline.json");
const baseline: Set<string> = new Set(
  (() => {
    try {
      return JSON.parse(readFileSync(BASELINE_PATH, "utf8")).undeclared as string[];
    } catch {
      return [] as string[];
    }
  })(),
);

const repoRoot = process.cwd();
const registry: Registry = JSON.parse(readFileSync(join(repoRoot, "prisma", "fk-registry.json"), "utf8"));
const schema = readFileSync(join(repoRoot, "prisma", "schema.prisma"), "utf8");

/** table -> the set of columns that appear as the SOURCE side of some declared constraint. */
const declared = new Map<string, Set<string>>();
for (const c of registry.constraints) {
  const set = declared.get(c.table) ?? new Set<string>();
  for (const col of c.columns) set.add(col);
  declared.set(c.table, set);
}

const models = [...schema.matchAll(/^model (\w+) \{([\s\S]*?)^\}/gm)];

const violations: string[] = [];
const unusedAllowances = new Set(ALLOWED.keys());
let checkedModels = 0;
let checkedColumns = 0;
let viaRelation = 0;
let viaRegistry = 0;
let softCount = 0;
let baselined = 0;
const stillBaselined = new Set<string>();

for (const [, model, body] of models) {
  // Global models have no tenantId and no composite FKs; Prisma relations cover them natively.
  const tableMatch = body.match(/@@map\("([^"]+)"\)/);
  const table = tableMatch ? tableMatch[1] : model;

  // Columns Prisma already covers via `@relation(fields: [...])`.
  const relationCovered = new Set<string>();
  for (const m of body.matchAll(/@relation\([^)]*fields:\s*\[([^\]]*)\]/g)) {
    for (const f of m[1].split(",")) relationCovered.add(f.trim());
  }

  const cols = [...body.matchAll(/^\s{2}(\w+)\s+String/gm)].map((m) => m[1]);
  const refCols = cols.filter((c) => /Id$/.test(c) && !NEVER_FK.has(c));
  if (refCols.length === 0) continue;
  checkedModels++;

  for (const col of refCols) {
    const key = `${model}.${col}`;
    if (ALLOWED.has(key)) {
      unusedAllowances.delete(key);
      continue;
    }
    if (softReason.has(col)) {
      softCount++;
      continue;
    }
    checkedColumns++;
    if (relationCovered.has(col)) {
      viaRelation++;
      continue;
    }
    if (declared.get(table)?.has(col)) {
      viaRegistry++;
      continue;
    }
    if (baseline.has(key)) {
      baselined++;
      stillBaselined.add(key);
      continue;
    }
    violations.push(`${model}.${col}  (table "${table}")`);
  }
}

if (unusedAllowances.size > 0) {
  console.error("✗ FK-1: stale ALLOWED entries (the column is gone or renamed) — remove them:");
  for (const k of unusedAllowances) console.error(`  ${k}`);
  process.exit(1);
}

const staleBaseline = [...baseline].filter((k) => !stillBaselined.has(k));
if (staleBaseline.length > 0) {
  console.error(
    `✗ FK-1: ${staleBaseline.length} baseline entr(ies) no longer apply — the column was constrained, ` +
      "renamed or removed. Delete them from prisma/fk-baseline.json so the ratchet cannot loosen:",
  );
  for (const k of staleBaseline) console.error(`  ${k}`);
  process.exit(1);
}

if (violations.length > 0) {
  console.error(
    `✗ FK-1: ${violations.length} reference column(s) are declared NEITHER as a Prisma \`@relation\` NOR ` +
      "as a constraint in prisma/fk-registry.json. Either the migration that should create the composite " +
      "FK was never written, or the registry is stale (re-run `npm run gen:fk-registry`), or the column " +
      "only looks like a foreign key — in which case add it to ALLOWED with the reason:",
  );
  for (const v of violations) console.error(`  ${v}`);
  process.exit(1);
}

console.log(
  `✓ FK-1: all ${checkedColumns} reference columns across ${checkedModels} models are declared ` +
    `(${viaRelation} via Prisma @relation, ${viaRegistry} via composite constraint), ` +
    `${softCount} soft by category, ${ALLOWED.size} allowed, ${baselined} on the shrink-only baseline.`,
);
process.exit(0);
